# Generated by Django 4.0.5 on 2022-07-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Organisme',
                'verbose_name_plural': 'Organismes',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Informationvcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nomar', models.CharField(blank=True, max_length=100, null=True)),
                ('prenomar', models.CharField(blank=True, max_length=100, null=True)),
                ('telephoneperso1', models.CharField(blank=True, max_length=100, null=True)),
                ('telephoneperso2', models.CharField(blank=True, max_length=100, null=True)),
                ('telephonepoerso3', models.CharField(blank=True, max_length=100, null=True)),
                ('emailperso', models.CharField(blank=True, max_length=100, null=True)),
                ('emailorganisme1', models.CharField(blank=True, max_length=100, null=True)),
                ('emailorganisme2', models.CharField(blank=True, max_length=100, null=True)),
                ('Adressepro', models.TextField(blank=True, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('cv_recto', models.FileField(upload_to='files', verbose_name='cv_recto')),
                ('cv_verso', models.FileField(blank=True, null=True, upload_to='files', verbose_name='cv_verso')),
                ('note', models.TextField(blank=True, null=True)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.organisme', verbose_name='Organisme')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.pays', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Carte de visite',
                'verbose_name_plural': 'Carte de visite',
                'ordering': ('nom',),
            },
        ),
    ]
