# Generated by Django 4.0.5 on 2022-07-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_remove_informationvcard_telephonepoerso3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationvcard',
            name='Adressepro',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='informationvcard',
            name='cv_recto',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Recto'),
        ),
        migrations.AlterField(
            model_name='informationvcard',
            name='emailorganisme1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email 1'),
        ),
        migrations.AlterField(
            model_name='informationvcard',
            name='emailorganisme2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email 2'),
        ),
        migrations.AlterField(
            model_name='informationvcard',
            name='emailperso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='informationvcard',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fax'),
        ),
    ]
