# Generated by Django 4.0.5 on 2022-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_informationvcard_adressepro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationvcard',
            name='site_web',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Site web'),
        ),
    ]
