# Generated by Django 4.0.5 on 2022-07-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_informationvcard_site_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationvcard',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
    ]
