# Generated by Django 4.0.5 on 2022-07-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_alter_informationvcard_telephonepro1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationvcard',
            name='emailorganisme1',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Email 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationvcard',
            name='emailorganisme2',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Email 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationvcard',
            name='emailperso',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationvcard',
            name='note',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationvcard',
            name='telephoneperso1',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Tél 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationvcard',
            name='telephoneperso2',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Tél 2'),
            preserve_default=False,
        ),
    ]
